### ISSUE TITLE
Problems with RSS from some major news cooperations

### ISSUE THREAD

**Issue by MortenGregersen** [brightdigit/SyndiKit#35]
I tried out SyndiKit in my app, where I want to parse the RSS feed from CNN and the national Danish broadcasting company 'DR'. Both fail. When I try an RSS feed from the national Swedish broadcasting company 'SVT', it works fine.

I can't seem to figure out, what the difference is, that makes CNN and DR fail.

The failing RSS feeds:
- http://rss.cnn.com/rss/cnn_latest.rss
- https://www.dr.dk/nyheder/service/feeds/senestenyt

The working RSS feed:
- https://www.svt.se/rss.xml

**Comment by leogdion** [comment]
thank @MortenGregersen for the update and my apologies for the inconvenience.
I'll take a look at it this week.

**Comment by leogdion** [comment]
How are you parsing it? I'm not having an issues with Cnn but I am having issues with DR. I'm using [the standard `decode` function](https://syndikit.work/documentation/syndikit/syndecoder/decode(_:)).

**Comment by leogdion** [comment]
Okay this is fix here:
https://github.com/brightdigit/SyndiKit/pull/36

I need to update the CI but expect this to be merged soon. Feel free to test with that branch. Your feedback would be helpful.

**Comment by leogdion** [comment]
@MortenGregersen  try version 0.3.0 and let me know if that doesn't fix the issue.

**Comment by MortenGregersen** [comment]
Thank @leogdion. I hope to test it in the weekend or in the start of the next week.

**Comment by MortenGregersen** [comment]
It works! 🎉
