### ISSUE TITLE
Parse Other Podcast Elements

### ISSUE THREAD

**Issue by leogdion** [brightdigit/SyndiKit#53]
```xml
<podcast:transcript url="https://share.transistor.fm/s/336118a1/transcript.srt" type="text/srt" rel="captions"/>
<podcast:chapters url="https://share.transistor.fm/s/336118a1/chapters.json" type="application/json+chapters"/>
```

**Comment by leogdion** [comment]
Here are notes on the podcast namespace:
https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#locked

**Comment by leogdion** [comment]
Use this one as a focus:
https://raw.githubusercontent.com/brightdigit/SyndiKit/main/Data/XML/empowerapps-show-cdata_summary.xml

**Comment by devahmedshendy** [comment]
Up to phase 2: https://github.com/Podcastindex-org/podcast-namespace#phase-2-closed-on-13121

**Comment by devahmedshendy** [comment]
https://wiki.openstreetmap.org/wiki/Elements

**Comment by devahmedshendy** [comment]
For this osm [R7444#188](https://www.openstreetmap.org/relation/7444/history), it seems like `revision` is a revision number:

<img width="332" alt="Screenshot 2023-09-27 at 3 32 41 AM" src="https://github.com/brightdigit/SyndiKit/assets/22206851/2cbad515-dec1-4289-af6b-52526d1eda53">
